name: Ajou Data Auto Update

on:
  schedule:
    - cron: '0 3,6,11,15,21 * * *' # 한국 시간 00:00, 06:00, 12:00, 15:00, 18:00
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    # 여기에 직접 권한을 부여합니다.
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Crawler
        run: python crawler.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/data/*.json
          git commit -m "Auto update data: $(date +'%Y-%m-%d')" || exit 0
          git push
