name: Ajou Notice Crawler

on:
  schedule:
    - cron: '0 15 * * *' # 한국 시간 00:00
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3 -> v4 업데이트

      - name: Set up Python
        uses: actions/setup-python@v5 # v4 -> v5 업데이트
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install firebase-admin requests beautifulsoup4

      - name: Run crawler
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: python crawl_to_firestore.py
